# Generated by Django 3.1.7 on 2021-05-26 00:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authy_id',
            field=models.CharField(blank=True, help_text='Authentication ID received from Twilio 2FA Api.', max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='authy_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='This phone number is dedicated to Twilio 2FA Authentication.', max_length=128, null=True, region=None, unique=True),
        ),
    ]
