# Generated by Django 3.1.7 on 2021-05-26 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210526_0052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id', 'username', 'first_name', 'last_name', 'email', 'authy_phone', 'is_active', 'is_staff', 'password'], 'verbose_name_plural': 'users'},
        ),
    ]
