# Generated by Django 3.1.7 on 2021-05-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210526_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='authy_id',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
