# Generated by Django 3.1.7 on 2021-05-26 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210526_0406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id', 'username', 'first_name', 'last_name', 'email', 'number', 'phone_verified', 'is_active', 'is_staff', 'password'), 'verbose_name_plural': 'users'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='authy_phone',
            new_name='number',
        ),
    ]
